### ISSUE TITLE
Erro inesperado com python 3.7 e asyncio.run 

### ISSUE THREAD

**Issue by diogommartins** [B2W-BIT/aiologger#11]
Passos para reproduzir no `aiologger==0.1.1-rc2` 
```python
import asyncio
import aiologger


logger = aiologger.Logger.with_default_handlers(level=10)

async def main():
    await asyncio.gather(
        *(logger.info("Python Brasil 2018 !") for _ in range(10000))
    )


asyncio.run(main())

```
Output:

```
Python Brasil 2018 !
Traceback (most recent call last):
  File "/Users/diogo/PycharmProjects/sandbox/com_aiologger.py", line 13, in <module>
    asyncio.run(main())
  File "/Users/diogo/.pyenv/versions/3.7.0/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Users/diogo/.pyenv/versions/3.7.0/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/Users/diogo/PycharmProjects/sandbox/com_aiologger.py", line 9, in main
    *(logger.info("Python Brasil 2018 !") for _ in range(10000))
  File "/Users/diogo/.local/share/virtualenvs/sandbox-JDY7YgCv/lib/python3.7/site-packages/aiologger/logger.py", line 200, in info
    await self._log(logging.INFO, msg, args, **kwargs)
  File "/Users/diogo/.local/share/virtualenvs/sandbox-JDY7YgCv/lib/python3.7/site-packages/aiologger/logger.py", line 176, in _log
    await self.handle(record)
  File "/Users/diogo/.local/share/virtualenvs/sandbox-JDY7YgCv/lib/python3.7/site-packages/aiologger/logger.py", line 97, in handle
    await self._initialize()
  File "/Users/diogo/.local/share/virtualenvs/sandbox-JDY7YgCv/lib/python3.7/site-packages/aiologger/logger.py", line 59, in _initialize
    async with self._initializing:
  File "/Users/diogo/.pyenv/versions/3.7.0/lib/python3.7/asyncio/locks.py", line 92, in __aenter__
    await self.acquire()
  File "/Users/diogo/.pyenv/versions/3.7.0/lib/python3.7/asyncio/locks.py", line 192, in acquire
    await fut
RuntimeError: Task <Task pending coro=<Logger.info() running at /Users/diogo/.local/share/virtualenvs/sandbox-JDY7YgCv/lib/python3.7/site-packages/aiologger/logger.py:200> cb=[gather.<locals>._done_callback() at /Users/diogo/.pyenv/versions/3.7.0/lib/python3.7/asyncio/tasks.py:660]> got Future <Future pending> attached to a different loop
/Users/diogo/.pyenv/versions/3.7.0/lib/python3.7/logging/__init__.py:1987: RuntimeWarning: coroutine 'AsyncStreamHandler.flush' was never awaited
  h.flush()
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/diogo/.pyenv/versions/3.7.0/lib/python3.7/logging/__init__.py", line 1988, in shutdown
    h.close()
  File "/Users/diogo/.local/share/virtualenvs/sandbox-JDY7YgCv/lib/python3.7/site-packages/aiologger/handlers.py", line 97, in close
    self.stream.close()
  File "/Users/diogo/.pyenv/versions/3.7.0/lib/python3.7/asyncio/streams.py", line 317, in close
    return self._transport.close()
  File "/Users/diogo/.pyenv/versions/3.7.0/lib/python3.7/asyncio/unix_events.py", line 707, in close
    self.write_eof()
  File "/Users/diogo/.pyenv/versions/3.7.0/lib/python3.7/asyncio/unix_events.py", line 693, in write_eof
    self._loop.call_soon(self._call_connection_lost, None)
  File "/Users/diogo/.pyenv/versions/3.7.0/lib/python3.7/asyncio/base_events.py", line 672, in call_soon
    self._check_closed()
  File "/Users/diogo/.pyenv/versions/3.7.0/lib/python3.7/asyncio/base_events.py", line 461, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

Funciona se mover a inicialização para um momento onde o loop está rodando

 ``` python
import asyncio
import aiologger


async def main():
    logger = aiologger.Logger.with_default_handlers(level=10)
    await asyncio.gather(
        *(logger.info("Python Brasil 2018 !") for _ in range(10000))
    )


asyncio.run(main())

```

**Comment by Mdslino** [comment]
Eu tive o mesmo problema com o loop em execução.

**Comment by daltonmatos** [comment]
> Eu tive o mesmo problema com o loop em execução.

Oi @Mdslino, interessante!

Você consegue montar um cenário onde é possível reproduzir esse bug? Isso ajudaria muito na implementação de uma correção.

**Comment by Mdslino** [comment]
Estou tentando montar um snippet aqui agora pra isso, aconteceu em uma aplicação do trabalho, então não posso compartilhar. Mas replicando aqui compartilho, inclusive já fiz fork para tentar uma possível correção.

**Comment by Mdslino** [comment]
`from aiologger.loggers.json import JsonLogger
import asyncio


async def log_info():
    logger = await JsonLogger.with_default_handlers(level=10)
    for i in range(100):
        await logger.info({'message': i})
    a = 5 / 0
    await logger.info({'message': a})


if __name__ == '__main__':
    asyncio.run(log_info())
`
O erro aparentemente acontece quando ocorre uma exception ou parada abrupta na aplicação, nesse exemplo que enviei é uma exception, mas o código que me fez investigar isso foi a finalização da execução do programa.

**Comment by Mdslino** [comment]
Pelo que andei investigando o erro acontece pelo seguinte motivo nesse contexto:

Quando a aplicação é encerrada a função shutdown invocada é a do Logger da lib built-in, porém o handler passado para essa função é o handler assíncrono da lib, e como as expressões são síncronas esse erro aparece. Uma solução é dar um shutdown manual no logger instanciado ou fazer essa correção a nível de implementação. Se conseguir alguma solução abro a PR.

**Comment by daltonmatos** [comment]
@Mdslino, @diogommartins, @dnp1 

Descobri que o loop do asyncio possui callback para tratamento de exceções não capturadas. Essa é a 
doc: https://docs.python.org/3/library/asyncio-eventloop.html#error-handling-api

Essa seria a solução perfeita, mas....

A documentação é bem simples e o que eu entendi foi:
Quando uma exceção for capturada pelo loop de eventos, uma função escolhida por nós pode ser chamada e receberá essa exceção como parâmetro. Um código simples de exemplo (basaeado no testcase do @Mdslino):

```python
from aiologger.loggers.json import JsonLogger
import asyncio
import sys

async def log_info():
    logger = JsonLogger.with_default_handlers(level=10)
    await logger.info({'message': 0})
    a = 5 / 0

def _handler(loop, ctx):
    print ("_handler...")

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    handler = loop.get_exception_handler()
    loop.set_exception_handler(_handler)

    loop.run_until_complete(log_info())
```

O problema começa porque esse código **não funciona** como esperado, ou seja, a função `_handler(loop, ctx)` **não é chamada** mesmo tendo sido registrada com `loop.set_exception_handler(_handler)`.

```
{"logged_at": "2018-11-17T21:18:22.253818-02:00", "line_number": 8, "function": "log_info", "level": "INFO", "file_path": "/tmp/check.py", "msg": {"message": 0}}
Traceback (most recent call last):
  File "/tmp/check.py", line 26, in <module>
    loop.run_until_complete(log_info())
  File "/home/daltonmatos/.pyenv/versions/3.6.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/tmp/check.py", line 9, in log_info
    a = 5 / 0
ZeroDivisionError: division by zero
/home/daltonmatos/.pyenv/versions/3.6.6/lib/python3.6/logging/__init__.py:1944: RuntimeWarning: coroutine 'AsyncStreamHandler.flush' was never awaited
  h.flush()
```

Aqui vemos que o handler default rodou, que é quem printa o stacktrace.

Se mudamos a linha do `loop.run_until_complete(log_info())` para:

```
    loop.create_task(log_info())
    loop.run_forever()
```

Aí passa a funcionar e o `_handler` é corretamente chamado:

```
{"logged_at": "2018-11-17T21:20:22.064992-02:00", "line_number": 8, "function": "log_info", "level": "INFO", "file_path": "/tmp/check.py", "msg": {"message": 0}}
_handler...
```

Outra estranheza:

Se remover o `loop.run_forever()` o handler também não é chamado.

Isso já é problema suficiente pois como o aiologger é uma lib, não temos controle sobre como o código está startando o loop, se está usando `create_task() + run_forever()` por exemplo.

Outro problema é que o python não permite que múltiplos exceptions handlers sejam registrados. Se você chama `loop.set_exception_handler()` múltiplas vezes, apenas o último handler é chamado.

O máximo de "chaining" que você poder fazer é: seu handler customizado chamando o handler default.

Se isso funcionasse de forma consistente poderíamos até registrar nosso handler e dentro dele chamar `await h.flush()` , que é a corotina que não está sendo "awaitada". =D

Outras alternativas:

* Se o loop tiver callbacks para indicar que está em processo de shutdown, podemos nos inserrir aí;
* Se tivermos algum tipo de "destrutor assíncrono" do objeto `AsyncStreamHandler`, podemos chamar o flush aí também.
* Se só existrem destrutores síncronos, podemos tentar fazer um `loop.create_task(h.flush())`, mas pode não funcionar, já que o loop estará em processo de shutdown por causa da exception que ele capturou. Fiz alguns testes, mais detalhes abaixo.
* Podemos fazer o flush de tempos em tempos (se não for um problema chamá-alo múltiplas vezes, claro). por exemplo podemos chamar o `flush()` a cada X (sendo `X  > 1`) logs gerados, ou até mesmo em um caso mais extremo, usar `X=1` mesmo.

## Sobre criar uma task dentro do handler

Fiz alguns testes:

Se o handler não faz nada com o loop, o programa **não morre**. Ou seja, parece ser responsabilidade do handler fazer o shutdown do loop. Então baseado nisso, dá pra encadear múltiplos handlers com `create_task()`, mas nenhum deles pode fazer `loop.stop()`.

Se o handler for:

```python
def _handler(loop, ctx):
    print ("_handler...")
    loop.create_task(_handler2(loop, ctx))
    loop.stop()

def _handler2(loop, ctx):
    print("_handler2...")

```

Os dois handlers rodam e o programa só acaba depois disso, MAS isso só acontece pois os handlers são **síncronos** e isso trava o loop. Se fazemos assim:

```python
def _handler(loop, ctx):
    print ("_handler...")
    loop.create_task(_handler2(loop, ctx))
    loop.stop()

def _handler2(loop, ctx):
    print("_handler2...")
    loop.create_task(asyncio.sleep(5))
```

O `asyncio.sleep(5)` **não executa**. Se existir uma forma de pedir ao loop para esperar por todas as tasks que estão ainda rodando/por rodar talvez seja uma forma boa de terminar o loop, mas provavelmente esse método de "esperar" vai ser assíncrono e como estamos dentro de uma função **síncrona**, não vamos poder fazer `await loop.<wait-for-coros>()`.

E aí o que acham?
