### ISSUE TITLE
Incompatibilidade uvloop + múltiplos loggers

### ISSUE THREAD

**Issue by lemosflavio** [B2W-BIT/aiologger#42]
Ao utilizar o `uvloop` e o `aiologger` com mais de uma instância dele estou recebendo o erro de `FileExistsError`. Ao que me parece a 2° instância não está conseguindo escrever/associar ao mesmo arquivo de escrita.

```python
import asyncio
import uvloop

from aiologger.loggers.json import JsonLogger

asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

logger = JsonLogger.with_default_handlers()
logger2 = JsonLogger.with_default_handlers()

async def to_log():
    await logger.error('Meu erro')
    await logger.debug('Meu debug')

    await logger2.error('Meu erro')
    await logger2.debug('Meu debug')

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(to_log())
    asyncio.get_event_loop().run_until_complete(logger.shutdown())
```

**Output**

```
{"logged_at": "2019-01-24T11:18:37.137866-02:00", "line_number": 13, "function": "to_log", "level": "DEBUG", "file_path": "/scratch.py", "msg": "Meu debug"}
{"logged_at": "2019-01-24T11:18:37.136690-02:00", "line_number": 12, "function": "to_log", "level": "ERROR", "file_path": "/scratch.py", "msg": "Meu erro"}
Traceback (most recent call last):
  File "/scratch.py", line 15, in to_log
    await logger2.error('Meu erro2')
  File "/aiologger/loggers/json.py", line 131, in _log
    await self.handle(record)
  File "/aiologger/logger.py", line 91, in handle
    await self.callHandlers(record)
  File "/aiologger/logger.py", line 75, in callHandlers
    await handler.handle(record)
  File "/aiologger/handlers.py", line 78, in handle
    await self.emit(record)
  File "/aiologger/handlers.py", line 89, in emit
    self.writer = await self._init_writer()
  File "/aiologger/handlers.py", line 46, in _init_writer
    self.protocol_class, self.stream
  File "uvloop/loop.pyx", line 2650, in connect_write_pipe
  File "uvloop/loop.pyx", line 2645, in uvloop.loop.Loop.connect_write_pipe
  File "uvloop/handles/pipe.pyx", line 168, in uvloop.loop.WriteUnixTransport._open
  File "uvloop/handles/pipe.pyx", line 29, in uvloop.loop.__pipe_open
FileExistsError: [Errno 17] File exists
```

**Comment by muzico425** [comment]
version 0.3.0 hava a bug,im back to version 0.2.3 ok.

**Comment by diogommartins** [comment]
Fixed at #40

**Comment by madkote** [comment]
@diogommartins faced same issue, with default asyncio loop...
