### ISSUE TITLE
Unknown if error or my inexperice is showing.

### ISSUE THREAD

**Issue by Judetg** [B2W-BIT/aiologger#53]
So when i run my script it gives me back this : 
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\jtgon\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File ".\discord_bot.py", line 49, in on_ready
    await logger.info(f'Channel ', channel, ' found')
  File "C:\Users\jtgon\AppData\Local\Programs\Python\Python36\lib\site-packages\aiologger\logger.py", line 132, in _log
    await self.handle(record)
  File "C:\Users\jtgon\AppData\Local\Programs\Python\Python36\lib\site-packages\aiologger\logger.py", line 91, in handle
    await self.callHandlers(record)
  File "C:\Users\jtgon\AppData\Local\Programs\Python\Python36\lib\site-packages\aiologger\logger.py", line 75, in callHandlers
    await handler.handle(record)
  File "C:\Users\jtgon\AppData\Local\Programs\Python\Python36\lib\site-packages\aiologger\handlers\streams.py", line 78, in handle
    await self.emit(record)
  File "C:\Users\jtgon\AppData\Local\Programs\Python\Python36\lib\site-packages\aiologger\handlers\streams.py", line 89, in emit
    self.writer = await self._init_writer()
  File "C:\Users\jtgon\AppData\Local\Programs\Python\Python36\lib\site-packages\aiologger\handlers\streams.py", line 46, in _init_writer
    self.protocol_class, self.stream
  File "C:\Users\jtgon\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 1133, in connect_write_pipe
    transport = self._make_write_pipe_transport(pipe, protocol, waiter)
  File "C:\Users\jtgon\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 353, in _make_write_pipe_transport
    raise NotImplementedError
NotImplementedError

And when I close it out it gives me this: 
C:\Users\jtgon\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py:1945: RuntimeWarning: coroutine 'AsyncStreamHandler.flush' was never awaited
  h.flush()
C:\Users\jtgon\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py:1946: RuntimeWarning: coroutine 'AsyncFileHandler.close' was never awaited
  h.close()
C:\Users\jtgon\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py:1946: RuntimeWarning: coroutine 'AsyncStreamHandler.close' was never awaited
  h.close()

My only assumption is that I did something writing when writing the bot.
Could also be that I just an too novice to try messing with your guys work.
Regardless I would appreciate the help and the dropping of knowledge. I'll attach the script too.
Thank you again in advanced!
[discord_bot - Copy.zip](https://github.com/B2W-BIT/aiologger/files/2928167/discord_bot.-.Copy.zip)

**Comment by diogommartins** [comment]
Hi @Judetg, i don't think that there's anything wrong with your code. The problem seems to be related with you environment, as aiologger currently isn't compatible with windows. Take a look at #12 for more on the subject

**Comment by diogommartins** [comment]
I'm closing windows related issues. If someone wants to develop and maintain windows compatibility, we can reopen it
