### ISSUE TITLE
I can't open dicom in python

### ISSUE THREAD

**Issue by Kepler-python** [B2W-BIT/aiologger#72]
I am trying to open a dicom files on Python 3.7 on windows but when i run my script : 

```
import pydicom
import numpy
from matplotlib import pyplot

dcm_image=pydicom.dcmread(r'C:\Users\Me\Documents\Internship\base_donnee\fichier_dicom\cou46 F 68A\DICOM\EXP00000\EXP0010.dcm')
img=dcm_image.pixel_array
plt.imshow(img,cmap='gray'),plt.title('Original Image')
plt.show()
```
I have this message : 

> Traceback (most recent call last):
  File "<tmp 1>", line 7, in <module>
    img=dcm_image.pixel_array
  File "c:\users\me\appdata\local\programs\python\python37\lib\site-packages\pydicom\dataset.py", line 949, in pixel_array
    self.convert_pixel_data()
  File "c:\users\me\appdata\local\programs\python\python37\lib\site-packages\pydicom\dataset.py", line 895, in convert_pixel_data
    raise last_exception
  File "c:\users\me\appdata\local\programs\python\python37\lib\site-packages\pydicom\dataset.py", line 863, in convert_pixel_data
    arr = handler.get_pixeldata(self)
  File "c:\users\me\appdata\local\programs\python\python37\lib\site-packages\pydicom\pixel_data_handlers\pillow_handler.py", line 199, in get_pixeldata
    raise NotImplementedError(e.strerror)
NotImplementedError: None

> 
Can you explain me why please

**Comment by daltonmatos** [comment]
Hello @Kepler-python,

Is this your full script? What I'm trying to do is find out what is the relation of this script wirh the `aiologger` project.

Could you show me where are you using `aiologger` in your code?

Thanks,

**Comment by Kepler-python** [comment]
At first glance, I am at the wrong place to post my question, 
sorry I will close the post.

**Comment by daltonmatos** [comment]
No problem @Kepler-python. I will close it for you.

Thanks.
