### ISSUE TITLE
ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by madkote** [B2W-BIT/aiologger#89]
python: 3.7
aiologger: 0.4.0

I have some difficulty to understand what happens here (see code below).
In short:
* create a logger `logger2`
* log with `logger2`
* shutdown `logger2`
* create a logger `logger2`
* log with `logger2` ---> ERROR

```
okay
okay
[<$AsyncStreamHandler ($DEBUG)>]
okay 1
okay 2
{"msg": "hello debug - 1"}
{"msg": "hello debug - 2"}
okay logging
Traceback (most recent call last):
  File "demo_async.py", line 497, in <module>
    run()
  File "demo_async.py", line 492, in run
    loop.run_until_complete(main_bug(loop=loop))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "demo_async.py", line 402, in main_bug
    await logger2.debug('hello debug - 2')
  File "/home/madkote/code/test_logging/venv/lib/python3.7/site-packages/aiologger/loggers/json.py", line 111, in _log
    await self.handle(record)
  File "/home/madkote/code/test_logging/venv/lib/python3.7/site-packages/aiologger/logger.py", line 184, in handle
    await self.call_handlers(record)
  File "/home/madkote/code/test_logging/venv/lib/python3.7/site-packages/aiologger/logger.py", line 154, in call_handlers
    await handler.handle(record)
  File "/home/madkote/code/test_logging/venv/lib/python3.7/site-packages/aiologger/handlers/streams.py", line 68, in handle
    await self.emit(record)
  File "/home/madkote/code/test_logging/venv/lib/python3.7/site-packages/aiologger/handlers/streams.py", line 79, in emit
    self.writer = await self._init_writer()
  File "/home/madkote/code/test_logging/venv/lib/python3.7/site-packages/aiologger/handlers/streams.py", line 50, in _init_writer
    self.protocol_class, self.stream
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1450, in connect_write_pipe
    transport = self._make_write_pipe_transport(pipe, protocol, waiter)
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 180, in _make_write_pipe_transport
    return _UnixWritePipeTransport(self, pipe, protocol, waiter, extra)
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 555, in __init__
    self._fileno = pipe.fileno()
ValueError: I/O operation on closed file
Exception ignored in: <function _UnixWritePipeTransport.__del__ at 0x7fe9b8fb2ef0>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 711, in __del__
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 592, in __repr__
AttributeError: '_UnixWritePipeTransport' object has no attribute '_closing'
```

Code to reproduce
```
import asyncio
import json
import logging
import sys

from aiologger.loggers.json import JsonLogger
from aiologger.formatters.json import JsonFormatter

async def main_bug(loop):
    transport, protocol = await loop.connect_write_pipe(asyncio.Protocol, sys.stdout)
    print("okay")
    transport2, protocol2 = await loop.connect_write_pipe(asyncio.Protocol, sys.stdout)
    print("okay")

    name = __name__
    level = logging.DEBUG
    stream = sys.stdout

    logger1 = JsonLogger(name=name + '_1', level=level, loop=loop)
    formatter = JsonFormatter(serializer=json.dumps)
    logger1.add_handler(
        AsyncStreamHandler(
            stream=stream,
            level=level,
            formatter=formatter,
            loop=loop,
        )
    )
    print(logger1.handlers)
    print('okay 1')
    logger2 = JsonLogger(name=name + '_2', level=level, loop=loop)
    formatter = JsonFormatter(serializer=json.dumps)
    logger2.add_handler(
        AsyncStreamHandler(
            stream=stream,
            level=level,
            formatter=formatter,
            loop=loop,
        )
    )
    print('okay 2')
    #
    await logger1.debug('hello debug - 1')
    await logger2.debug('hello debug - 2')
    print('okay logging')
    #
    await logger2.shutdown()  # TODO: xxx !!!
    #
    # TODO: xxx !!! create a new logger instance with same var-name !!!
    # if new logger with name logger3 is created then the issue is gone !!!
    logger2 = JsonLogger(name=name + '_2', level=level, extra=None, loop=loop)
    formatter = JsonFormatter(serializer=json.dumps)
    logger2.add_handler(
        AsyncStreamHandler(
            stream=stream,
            level=level,
            formatter=formatter,
            filter=None,
            loop=loop,
        )
    )
    await logger2.debug('hello debug - 2')
    #
    await logger1.shutdown()
    await logger2.shutdown()
    print('okay shutdown')

loop = asyncio.get_event_loop()
loop.run_until_complete(main_bug(loop=loop))
loop.close()
```

**Comment by madkote** [comment]
could be related to #42

**Comment by dnp1** [comment]
I'm facing the same issue here intermittently.

Environment: AWS Amazon Lambda with python 3.8
Logger Version: aiologger 0.6

**Comment by daltonmatos** [comment]
Hello @dnp1,

What EventoLoop implementation are you using?

**Comment by dnp1** [comment]
I'm using standard event loop.

here is my Pipfile.lock 

https://gist.github.com/dnp1/6212454dde8e72b05079b33da9c51274



I'll provide a complete stack trace as soon as possible.

**Comment by dnp1** [comment]
Follow my stacktrace
```
{
  "errorMessage": "I/O operation on closed file",
  "errorType": "ValueError",
  "stackTrace": [
    "  File \"/var/task/src/clubbi/lambdas/generate_shopper_plan.py\", line 24, in handle\n    asyncio.run(_handle(options))\n",
    "  File \"/var/lang/lib/python3.8/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n",
    "  File \"/var/lang/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n    return future.result()\n",
    "  File \"/var/task/src/clubbi/lambdas/generate_shopper_plan.py\", line 49, in _handle\n    shopper_plans = await handler.calculate_plans(options)\n",
    "  File \"/var/task/src/clubbi/domain/shopper_plan.py\", line 66, in calculate_plans\n    await self._logger.info(dict(message='plan splitted',\n",
    "  File \"/var/task/aiologger/logger.py\", line 177, in handle\n    await self.call_handlers(record)\n",
    "  File \"/var/task/aiologger/logger.py\", line 147, in call_handlers\n    await handler.handle(record)\n",
    "  File \"/var/task/aiologger/handlers/streams.py\", line 66, in handle\n    await self.emit(record)\n",
    "  File \"/var/task/aiologger/handlers/streams.py\", line 77, in emit\n    self.writer = await self._init_writer()\n",
    "  File \"/var/task/aiologger/handlers/streams.py\", line 50, in _init_writer\n    transport, protocol = await loop.connect_write_pipe(\n",
    "  File \"/var/lang/lib/python3.8/asyncio/base_events.py\", line 1541, in connect_write_pipe\n    transport = self._make_write_pipe_transport(pipe, protocol, waiter)\n",
    "  File \"/var/lang/lib/python3.8/asyncio/unix_events.py\", line 183, in _make_write_pipe_transport\n    return _UnixWritePipeTransport(self, pipe, protocol, waiter, extra)\n",
    "  File \"/var/lang/lib/python3.8/asyncio/unix_events.py\", line 579, in __init__\n    self._fileno = pipe.fileno()\n"
  ]
}
```

**Comment by dnp1** [comment]
Maybe it is related to this one? https://bugs.python.org/issue37773

**Comment by dnp1** [comment]
I removed the aiologger from my code and the problem stopped.

I will try figure out what it could be but didn't understood.

I will extract  in which python version  it is happing logging it.  I know it is 3.8 but it never happens in my machine.

As long as lambda are delegated to random machines, it is possible some of them have python 3.8.6 and other 3.8.1, I do not know.

**Comment by daltonmatos** [comment]
Hello @dnp1, 

Thanks for taking your time to look into this. 🎉

The error happens to your code in exact same situation described originally in this issue? 

Creating a second logger instance using the same name of an already shutdown logger.

Thanks,

**Comment by dnp1** [comment]
Hello @daltonmatos 

Originally I had 4 different JsonLoggers instances and I thought it was the same situation, but In my last test I kept only one logger and it continued happening. I'll try a simpler code, without any business logic and will run into lambda until get a proper pattern.
