### ISSUE TITLE
does `shutdown()` shutsdown completely?

### ISSUE THREAD

**Issue by madkote** [B2W-BIT/aiologger#90]
python: 3.7
aiologger: 0.4.0

when calling a function with `shutdown()` inside more then once, logging breaks.
Is it a wanted feature?

error:
```
<_UnixSelectorEventLoop running=False closed=False debug=False> <class 'asyncio.unix_events._UnixSelectorEventLoop'>
okay
okay
[<$AsyncStreamHandler ($DEBUG)>]
okay 1
okay 2
{"msg": "hello debug - 1"}
{"msg": "hello debug - 2"}
okay logging
okay shutdown
Traceback (most recent call last):
  File "demo_async.py", line 565, in <module>
    run()
  File "demo_async.py", line 556, in run
    loop.run_until_complete(main_bug_second(loop=loop))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "demo_async.py", line 412, in main_bug_second
    asyncio.Protocol, sys.stdout
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1450, in connect_write_pipe
    transport = self._make_write_pipe_transport(pipe, protocol, waiter)
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 180, in _make_write_pipe_transport
    return _UnixWritePipeTransport(self, pipe, protocol, waiter, extra)
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 555, in __init__
    self._fileno = pipe.fileno()
ValueError: I/O operation on closed file
Exception ignored in: <function _UnixWritePipeTransport.__del__ at 0x7f80ae77ef80>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 711, in __del__
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 592, in __repr__
AttributeError: '_UnixWritePipeTransport' object has no attribute '_closing'
```

code:
```
async def main_bug_second(loop):
    transport, protocol = await loop.connect_write_pipe(
        asyncio.Protocol, sys.stdout
    )
    print("okay")

    transport2, protocol2 = await loop.connect_write_pipe(
        asyncio.Protocol, sys.stdout
    )
    print("okay")

    name = __name__
    level = logging.DEBUG
    stream = sys.stdout

    logger1 = JsonLogger(name=name + '_1', level=level, loop=loop)
    formatter = JsonFormatter(serializer=json.dumps)
    logger1.add_handler(
        AsyncStreamHandler(
            stream=stream,
            level=level,
            formatter=formatter,
            loop=loop,
        )
    )
    print(logger1.handlers)
    print('okay 1')
    logger2 = JsonLogger(name=name + '_2', level=level, loop=loop)
    formatter = JsonFormatter(serializer=json.dumps)
    logger2.add_handler(
        AsyncStreamHandler(
            stream=stream,
            level=level,
            formatter=formatter,
            loop=loop,
        )
    )
    print('okay 2')
    #
    await logger1.debug('hello debug - 1')
    await logger2.debug('hello debug - 2')
    print('okay logging')
    #
    await logger1.shutdown()
    await logger2.shutdown()
    print('okay shutdown')

loop = asyncio.get_event_loop()
print(loop, type(loop))
loop.run_until_complete(main_bug_second(loop=loop))
loop.run_until_complete(main_bug_second(loop=loop))
loop.close()
```

**Comment by daltonmatos** [comment]
Hello @madkote,

Thanks for reporting this issue. I'm taking a look at this and indeed this seems very wrong. I will soon post what else I discovered during my analisys.

If you are having production problems because of this behavior one way to mitigate this is to create global loggers and call their `shutdown()` method only when exiting your program.

thanks,

**Comment by madkote** [comment]
@daltonmatos thx for looking into. this was just a hypothetical use case.

**Comment by daltonmatos** [comment]
Hello @madkote,

I reduced the code a bit and it is still able to reproduce the crash. Here it is.

```python
import asyncio
import json
import logging
import sys

from aiologger.formatters.json import JsonFormatter
from aiologger.handlers.streams import AsyncStreamHandler
from aiologger.loggers.json import JsonLogger


async def main_bug_second(loop):
    name = __name__
    level = logging.DEBUG
    stream = sys.stdout

    logger1 = JsonLogger(name=name + "_1", level=level, loop=loop)
    formatter = JsonFormatter(serializer=json.dumps)
    logger1.add_handler(
        AsyncStreamHandler(
            stream=stream, level=level, formatter=formatter, loop=loop
        )
    )

    logger2 = JsonLogger(name=name + "_2", level=level, loop=loop)
    formatter = JsonFormatter(serializer=json.dumps)
    logger2.add_handler(
        AsyncStreamHandler(
            stream=stream, level=level, formatter=formatter, loop=loop
        )
    )

    await logger1.debug("hello debug - 1")
    await logger2.debug("hello debug - 2")

    await logger1.shutdown()
    await logger2.shutdown()
    print("##################")


async def main(loop):
    print("BEFORE")
    await main_bug_second(loop)
    print("AFTER")
    # await main_bug_second(loop)


loop = asyncio.get_event_loop()
loop.run_until_complete(main(loop=loop))

```

This code the way it is now (calling `main_bug_second()` only once) does not crash, but here is some interesting points.

- The problem seems not to be the multiple instances os the loggers. We can create two loggers and use both. The `print("####")` works and also the print outside the function (`print("AFTER")`) works too.
- If the comment the line ` await logger2.shutdown()` the `print("AFTER")` does not work anymore. Which means that a simple `print()` isn't able to write to `stdout`.
- If we declare only one logger, but calls `main_bug_second()` twice, it crashes. And crashes when calling `loop.connect_write_pipe()` but a `print()` **inside** `main_bug_second()` works!!!

## My Doubts
- What's the difference between a `print()` do `stdout` and a `loop.connect_write_pipe()` on this same `stdout`? Why a print works but the `connect_write_pipe` doesn't, even using the same `stdout`?
- Why not calling logger `shutdown()` leaves `stdout` in a state that even `print()` can't use?

**Comment by daltonmatos** [comment]
Even the `print("INNER")` working (on the second call to `main_bug_second()` when we get to `AsyncStreamHandler._init_writer()`, `print()` does not work any more.

I compared `id(sys.stdout)` to `id(self.stream)` (inside `AsyncStreamHandler`) and they are the same. Maybe something in the way between the first line of `main_bug_second()` and `AsyncStreamHandler._init_writer()` is closing the file descriptor.

**Comment by daltonmatos** [comment]
I'm pinging @diogommartins to see what he thinks about this.

**Comment by madkote** [comment]
@daltonmatos thx for summary and looking into. Yes, I guess that `sys.stdout` is closed and not usable anymore after `shutdown()`

**Comment by daltonmatos** [comment]
> Yes, I guess that `sys.stdout` is closed and not usable anymore after `shutdown()`

It is odder than this. Because even after calling `await logger1.shutdown()` the following line, `print("######")` **works**! 

Even on the second call to `main_bug_second()` a `print()` on the first line of this function **works** but the call to `connect_write_pipe()` fails.

**Comment by madkote** [comment]
@daltonmatos @diogommartins the issue seems to be **critical**:
```If you are having production problems because of this behavior one way to mitigate this is to create global loggers and call their shutdown() method only when exiting your program.```

the above will not work in a simple web app when using `gunicorn`:
* `master` logger is shutdown in one process
* gunicorn process will crash, because it also tries to log to stdout (by default), which is closed.

**Comment by madkote** [comment]
@daltonmatos @diogommartins just FYI: the default `logging.StreamHandler` does never close the stream - only `FileHandler` does it.

the `close()` function of stream handler is only:
```    def close(self):
        """
        Tidy up any resources used by the handler.

        This version removes the handler from an internal map of handlers,
        _handlers, which is used for handler lookup by name. Subclasses
        should ensure that this gets called from overridden close()
        methods.
        """
        #get the module data lock, as we're updating a shared structure.
        _acquireLock()
        try:    #unlikely to raise an exception, but you never know...
            if self._name and self._name in _handlers:
                del _handlers[self._name]
        finally:
            _releaseLock()
```

**I guess that could be the fix**. It is too late now for me to validate and create a possible PR.

**Comment by daltonmatos** [comment]
Indeed this is critical and not closing the stream in the case of a StreamHandler indeed makes sense. Would you have an example gunicorn config + app code so I can validate if this implementation would work?

What makes me think that this could be a trickier problem is that even when the code does not call `.shutdown()` the same error happens on the second call to `main_bug_second()`.
